# Generated by Django 3.1.4 on 2020-12-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0002_auto_20201214_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10, unique=True)),
                ('subject_name', models.CharField(max_length=200, unique=True)),
                ('Description', models.CharField(default=' ', max_length=200)),
                ('Uploaded_on', models.DateField(auto_now_add=True)),
                ('subject_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Branch_subject', to='vtu.masterbranches')),
                ('subject_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semester_subject', to='vtu.mastersemesters')),
            ],
        ),
    ]
