# Generated by Django 3.1.4 on 2020-12-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0003_mastersubjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternotes',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Master_owner', to='vtu.mastersubjects'),
        ),
    ]
