# Generated by Django 3.1.4 on 2020-12-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0004_masternotes_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternotes',
            name='author',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AddField(
            model_name='masternotes',
            name='file_snippet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
