# Generated by Django 3.1.4 on 2020-12-17 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vtu', '0005_auto_20201216_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterQuestionPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('file_snippet', models.FileField(blank=True, null=True, upload_to='')),
                ('Description', models.CharField(default=' ', max_length=200)),
                ('Uploaded_on', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Branch_question', to='vtu.masterbranches')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_question', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semester_question', to='vtu.mastersemesters')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Master_question', to='vtu.mastersubjects')),
            ],
        ),
    ]
