# Generated by Django 3.1.4 on 2021-01-01 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vtu', '0006_masterquestionpapers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProgramId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programid', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_question', to='vtu.masterbranches')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_question', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_question', to='vtu.mastersemesters')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_question', to='vtu.mastersubjects')),
            ],
        ),
    ]
