# Generated by Django 3.1.4 on 2021-01-01 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vtu', '0007_masterprogramid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterVideoLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('views', models.IntegerField(default=0)),
                ('description', models.CharField(default=' ', max_length=400)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videolab_question', to='vtu.masterbranches')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videolab_owner', to=settings.AUTH_USER_MODEL)),
                ('programid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videolab_question', to='vtu.masterprogramid')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videolab_question', to='vtu.mastersemesters')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videolab_question', to='vtu.mastersubjects')),
            ],
        ),
    ]
