# Generated by Django 3.1.4 on 2021-01-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0009_auto_20210101_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastervideolab',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
