# Generated by Django 3.1.4 on 2021-01-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0010_mastervideolab_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppForceUpdateRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_update_required', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default=' ', max_length=16)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(default=' ', max_length=16)),
                ('mapped_key', models.CharField(default=' ', max_length=16)),
            ],
        ),
    ]
