# Generated by Django 3.1.4 on 2021-01-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtu', '0013_mastersyllabuscopy_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=40)),
                ('designation', models.CharField(default=' ', max_length=40)),
                ('about', models.CharField(default=' ', max_length=80)),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
